root: true
extends:
  - @react-native-community
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier
  - plugin:react/recommended
  - airbnb
  - airbnb/hooks

settings:
  react:
    - pragma: React
    - fragment: Fragment
    - version: detect